# Taps
tap "homebrew/cask"
tap "AdoptOpenJDK/openjdk"
tap "universal-ctags/universal-ctags"

# Languages
cask "adoptopenjdk11"
brew "go"
brew "node"
brew "python"
brew "typescript"

# Tools
brew "htop"
brew "jq"
brew "kube-ps1"
brew "kubectx"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "kustomize"
brew "mercurial"
brew "nmap"
brew "octant"
brew "operator-sdk"
brew "terraform"
brew "tmux"
brew "tree"
brew "universal-ctags", args: ['HEAD']
brew "vault"
brew "watch"
brew "wget"
brew "yamllint"
brew "zsh"
brew "zsh-completions"

# Desktop Applications
cask "1password"
cask "alfred"
cask "appcleaner"
cask "docker"
cask "forklift"
cask "google-chrome"
cask "intellij-idea"
cask "iterm2"
cask "mongodb-compass-community"
cask "postman"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "tunnelblick"
cask "visual-studio-code"
cask "zoomus"
