# Languages
brew "go"
brew "deno"
# After node was installed we have to link it and we have to install yarn:
#   brew link --force --overwrite node@20
#   npm install --global yarn
brew "node@20"

# Tools
brew "btop"
brew "fd"
brew "fluxcd/tap/flux"
brew "fzf"
brew "gh"
brew "helm"
brew "jq"
brew "kind"
brew "kubectx"
brew "kubernetes-cli"
brew "kustomize"
brew "krew"
brew "neovim"
brew "operator-sdk"
brew "rclone"
brew "ripgrep"
brew "starship"
brew "stylua"
brew "telnet"
brew "terraform"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yazi"
brew "yq"
brew "zsh"
brew "zsh-completions"
